project:
  type: website
  output-dir: docs

website:
  title: "Learning Voronoi Treemap - Initiative"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
